# Generated by Django 4.1.6 on 2023-02-09 02:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, max_length=225, null=True, populate_from='category_name', unique=True),
        ),
    ]
